/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvocateRouteImport } from './routes/advocate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LecturesRouteImport } from './routes/lectures'
import { Route as NeurofeedbackRouteImport } from './routes/neurofeedback'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SpeakingRouteImport } from './routes/speaking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvocateRoute = AdvocateRouteImport.update({
  id: '/advocate',
  path: '/advocate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturesRoute = LecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => rootRouteImport,
} as any)
const NeurofeedbackRoute = NeurofeedbackRouteImport.update({
  id: '/neurofeedback',
  path: '/neurofeedback',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocate': typeof AdvocateRoute
  '/contact': typeof ContactRoute
  '/lectures': typeof LecturesRoute
  '/neurofeedback': typeof NeurofeedbackRoute
  '/people': typeof PeopleRoute
  '/resources': typeof ResourcesRoute
  '/speaking': typeof SpeakingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocate': typeof AdvocateRoute
  '/contact': typeof ContactRoute
  '/lectures': typeof LecturesRoute
  '/neurofeedback': typeof NeurofeedbackRoute
  '/people': typeof PeopleRoute
  '/resources': typeof ResourcesRoute
  '/speaking': typeof SpeakingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocate': typeof AdvocateRoute
  '/contact': typeof ContactRoute
  '/lectures': typeof LecturesRoute
  '/neurofeedback': typeof NeurofeedbackRoute
  '/people': typeof PeopleRoute
  '/resources': typeof ResourcesRoute
  '/speaking': typeof SpeakingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advocate'
    | '/contact'
    | '/lectures'
    | '/neurofeedback'
    | '/people'
    | '/resources'
    | '/speaking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advocate'
    | '/contact'
    | '/lectures'
    | '/neurofeedback'
    | '/people'
    | '/resources'
    | '/speaking'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advocate'
    | '/contact'
    | '/lectures'
    | '/neurofeedback'
    | '/people'
    | '/resources'
    | '/speaking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvocateRoute: typeof AdvocateRoute
  ContactRoute: typeof ContactRoute
  LecturesRoute: typeof LecturesRoute
  NeurofeedbackRoute: typeof NeurofeedbackRoute
  PeopleRoute: typeof PeopleRoute
  ResourcesRoute: typeof ResourcesRoute
  SpeakingRoute: typeof SpeakingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advocate': {
      id: '/advocate'
      path: '/advocate'
      fullPath: '/advocate'
      preLoaderRoute: typeof AdvocateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures': {
      id: '/lectures'
      path: '/lectures'
      fullPath: '/lectures'
      preLoaderRoute: typeof LecturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neurofeedback': {
      id: '/neurofeedback'
      path: '/neurofeedback'
      fullPath: '/neurofeedback'
      preLoaderRoute: typeof NeurofeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvocateRoute: AdvocateRoute,
  ContactRoute: ContactRoute,
  LecturesRoute: LecturesRoute,
  NeurofeedbackRoute: NeurofeedbackRoute,
  PeopleRoute: PeopleRoute,
  ResourcesRoute: ResourcesRoute,
  SpeakingRoute: SpeakingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
